---
- hosts: node2
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
    - name: start service
      service:
        name: httpd
        state: started
